export const PATHS = {
  root: "/",
  dashboard: "/admin/dashboard",
  orders: "/admin/orders",
  customers: "/admin/customers",
  customerDetail: (id: string) => `/admin/customers/${id}`,
  categories: "/admin/categories",
  addCategory: "/admin/categories/new",
  blog: "/admin/blog",
  addBlog: "/admin/blog/new",
  transactions: "/admin/transactions",
  addProduct: "/admin/products/new",
  inventory: "/admin/products/inventory",
  adminRole: "/admin/admin-role",
  contactInbox: "/admin/contact-inbox",

  dev: {
    dashboard: "/dev/dashboard",
    orders: "/dev/orders",
    customers: "/dev/customers",
    categories: "/dev/categories",
    addCategory: "/dev/add-category",
    blog: "/dev/blog",
    addBlog: "/dev/add-blog",
    transactions: "/dev/transactions",
    addProduct: "/dev/add-product",
    inventory: "/dev/inventory",
    adminRole: "/dev/admin-role",
  },
} as const;
